#!/usr/bin/env python3
"""Index manager — creates and updates 00_INDEX health files for each person.

Called after a file is moved to its QSync destination.
Updates (or creates) the person's health index file with the new document entry.

Index files live at: E:/QSync/02-Areas/Family/<Person>/Health/00_INDEX_<Person>_Health.md
"""
from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Any


def update_health_index(qsync_root: Path, dest_path: Path, person: str, doc_type: str, description: str = "", extra_fields: dict | None = None) -> Path | None:
    """Update or create the person's health index file after a new document is added.

    Args:
        qsync_root: Path to E:/QSync
        dest_path: Full path to the moved file
        person: Person name (Daniel, Natalie, Isabella, etc.)
        doc_type: Document type (ERVisit, EyeExam, LabResult, etc.)
        description: Optional description for the index entry
        extra_fields: Optional dict of extra fields (reason_for_visit, final_diagnosis, physician, etc.)

    Returns:
        Path to the updated index file, or None on failure.
    """
    health_dir = qsync_root / "02-Areas" / "Family" / person / "Health"
    health_dir.mkdir(parents=True, exist_ok=True)
    index_path = health_dir / f"00_INDEX_{person}_Health.md"

    # Determine the sub-section from the dest_path relative to health_dir
    rel = dest_path.relative_to(health_dir) if str(dest_path).startswith(str(health_dir)) else dest_path.name
    parts = Path(str(rel)).parts
    # First part could be a subfolder like "Vision", "Hospitalization", "Dental", etc.
    subfolder = parts[0] if len(parts) > 1 and not parts[0].startswith("00_") else "."

    # Read existing index or create new
    if index_path.exists():
        content = index_path.read_text(encoding="utf-8")
    else:
        content = _new_index(person)

    # Build the entry line
    filename = dest_path.name
    entry_line = f"- `{filename}`"
    if description:
        entry_line += f" — {description}"
    if extra_fields:
        if extra_fields.get("reason_for_visit"):
            entry_line += f"\n  - Reason: {extra_fields['reason_for_visit']}"
        if extra_fields.get("final_diagnosis"):
            entry_line += f"\n  - Diagnosis: {extra_fields['final_diagnosis']}"
        if extra_fields.get("physician"):
            entry_line += f"\n  - Physician: {extra_fields['physician']}"

    # Find or create the section for this subfolder
    section_header = _section_header_for(subfolder, doc_type)
    content = _insert_entry(content, section_header, entry_line)

    # Update last-updated date
    today = datetime.now().strftime("%Y-%m-%d")
    content = re.sub(r"Last updated: \d{4}-\d{2}-\d{2}", f"Last updated: {today}", content)

    index_path.write_text(content, encoding="utf-8")
    return index_path


def _new_index(person: str) -> str:
    """Generate a fresh index template for a person."""
    today = datetime.now().strftime("%Y-%m-%d")
    return f"""# {person} — Health Index

Last updated: {today}

## Vision
Folder: `Vision/`

### Eye-Exams/
- *(empty — structure ready for future)*

## Dental
Folder: `Dental/`

### Records/
- *(empty — structure ready for future)*

## Hospitalization
Folder: `Hospitalization/`

- *(empty — structure ready for future)*

## ER Visits
Folder: `./` (root level)

- *(empty — structure ready for future)*

## Prescriptions
Folder: `Prescriptions/`

- *(empty — structure ready for future)*

## Providers
Folder: `Providers/`

- *(structure ready for future provider-specific docs)*

---

## Notes
- Medical bills live under: `04-Archives/Finance/Medical_Bills/{person}/<Year>/`
- Index auto-generated by Clawdy
"""


def _section_header_for(subfolder: str, doc_type: str) -> str:
    """Map subfolder/doc_type to the index section header."""
    mapping = {
        "Vision": "## Vision",
        "Dental": "## Dental",
        "Hospitalization": "## Hospitalization",
        "Hospitalization": "## Hospitalization",
        "Prescriptions": "## Prescriptions",
        "Providers": "## Providers",
        "School": "## School / Immunization",
    }
    # Check by subfolder first
    if subfolder in mapping:
        return mapping[subfolder]

    # Check by doc_type
    doc_type_lower = doc_type.lower() if doc_type else ""
    if "eye" in doc_type_lower or "vision" in doc_type_lower:
        return "## Vision"
    if "dental" in doc_type_lower or "dentist" in doc_type_lower:
        return "## Dental"
    if "hospital" in doc_type_lower or "ectopic" in doc_type_lower or "miscarriage" in doc_type_lower or "chest" in doc_type_lower:
        return "## Hospitalization"
    if "er" in doc_type_lower or "emergency" in doc_type_lower:
        return "## ER Visits"
    if "prescription" in doc_type_lower or "rx" in doc_type_lower:
        return "## Prescriptions"
    if "immunization" in doc_type_lower or "school" in doc_type_lower:
        return "## School / Immunization"

    # Default to ER Visits for root-level files
    if subfolder == ".":
        return "## ER Visits"

    return "## ER Visits"


def _insert_entry(content: str, section_header: str, entry_line: str) -> str:
    """Insert an entry line into the correct section of the index.

    If section exists, adds entry after the last existing entry in that section.
    If section doesn't exist, adds the section at the end.
    """
    lines = content.split("\n")
    section_start = None
    section_end = None

    for i, line in enumerate(lines):
        if line.strip().startswith(section_header):
            section_start = i
            continue
        if section_start is not None and line.startswith("## ") and i > section_start:
            section_end = i
            break

    if section_start is None:
        # Section not found — add it before the Notes section
        notes_idx = None
        for i, line in enumerate(lines):
            if line.strip().startswith("## Notes"):
                notes_idx = i
                break

        insert_at = notes_idx if notes_idx else len(lines)
        new_section = [section_header, "", entry_line, ""]
        lines = lines[:insert_at] + new_section + lines[insert_at:]
    else:
        # Find the last non-empty line in this section
        if section_end is None:
            section_end = len(lines)

        # Find last entry line (starts with "- " or "  -")
        last_entry = section_start
        for i in range(section_start, section_end):
            if lines[i].strip().startswith("- ") or lines[i].strip().startswith("  -"):
                last_entry = i

        # Insert after last entry + any continuation lines
        insert_at = last_entry + 1
        # Skip continuation lines (indented lines after an entry)
        while insert_at < section_end and (lines[insert_at].startswith("  ") or lines[insert_at].strip() == ""):
            if lines[insert_at].strip() == "" or lines[insert_at].startswith("  -"):
                insert_at += 1
            else:
                break

        # Remove "(empty — ...)" placeholder if present
        for i in range(section_start, section_end):
            if "*(empty" in lines[i] or "*(structure ready" in lines[i]:
                lines[i] = ""

        lines.insert(insert_at, entry_line)

    return "\n".join(lines)