#!/usr/bin/env python3
"""Generate 00_INDEX_<Person>_Health.md for a Health folder.

Scans the folder structure and creates a markdown index with quick links,
folder maps, and provider summaries.

Usage:
    python3 generate_health_index.py /path/to/Health/
"""
import sys
from pathlib import Path
from datetime import datetime


def generate_index(health_root: Path, person: str) -> str:
    """Generate markdown index for a Health folder."""
    lines = [
        f"# {person} — Health Index",
        "",
        f"Last updated: {datetime.now().strftime('%Y-%m-%d')}",
        "",
    ]

    # ── Quick links (high-value files at root level) ──
    root_files = sorted(f for f in health_root.iterdir() if f.is_file() and f.suffix.lower() in ('.pdf', '.jpg', '.jpeg', '.png', '.tif', '.tiff'))
    if root_files:
        lines.append("## Quick links (high value)")
        for f in root_files:
            lines.append(f"- {f.name}: `{f.name}`")
        lines.append("")

    # ── Subfolder sections ──
    subfolders = sorted(d for d in health_root.iterdir() if d.is_dir())
    
    # Section order
    section_order = ["Prescriptions", "Vision", "Dental", "Hospitalization", "Providers", "Lab"]
    
    ordered = []
    for section in section_order:
        for d in subfolders:
            if d.name.lower().startswith(section.lower()):
                ordered.append(d)
                break
    # Add any remaining folders
    for d in subfolders:
        if d not in ordered:
            ordered.append(d)

    for folder in ordered:
        name = folder.name
        lines.append(f"## {name}")
        lines.append(f"Folder: `{name}/`")
        lines.append("")

        # Check for immediate files
        immediate_files = sorted(f for f in folder.iterdir() if f.is_file())
        if immediate_files:
            for f in immediate_files:
                lines.append(f"- `{f.name}`")
            lines.append("")

        # List date-subfolders or provider subfolders
        child_dirs = sorted(d for d in folder.iterdir() if d.is_dir())
        for child in child_dirs:
            # Provider folder: list date subfolders
            date_subfolders = sorted(d for d in child.iterdir() if d.is_dir())
            if date_subfolders:
                lines.append(f"### {child.name}/")
                for date_dir in date_subfolders:
                    date_files = sorted(f for f in date_dir.iterdir() if f.is_file())
                    if date_files:
                        lines.append(f"**{date_dir.name}/**")
                        for f in date_files:
                            lines.append(f"- `{f.name}`")
                        lines.append("")
                # Also list any files directly in the provider folder
                provider_files = sorted(f for f in child.iterdir() if f.is_file())
                if provider_files:
                    lines.append(f"**Root files:**")
                    for f in provider_files:
                        lines.append(f"- `{f.name}`")
                    lines.append("")
            else:
                # Simple subfolder (like Dental/Records, Dental/Referrals, Vision/Eye-Exams)
                nested_files = sorted(f for f in child.iterdir() if f.is_file())
                if nested_files:
                    lines.append(f"### {child.name}/")
                    for f in nested_files:
                        lines.append(f"- `{f.name}`")
                    lines.append("")
                # Check for deeper nesting
                deep_dirs = sorted(d for d in child.iterdir() if d.is_dir())
                for dd in deep_dirs:
                    deep_files = sorted(f for f in dd.iterdir() if f.is_file())
                    if deep_files:
                        lines.append(f"**{dd.name}/**")
                        for f in deep_files:
                            lines.append(f"- `{f.name}`")
                        lines.append("")

    # ── Notes ──
    lines.append("---")
    lines.append("")
    lines.append("Notes")
    lines.append("- Medical bills live under: `04-Archives/Finance/Medical_Bills/{person}/<Year>/`")
    lines.append("- Provider-specific docs use `Providers/<Provider>/<Date>/` for fast retrieval")
    lines.append("- Index auto-generated by `generate_health_index.py`")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_health_index.py /path/to/Health/ [PersonName]")
        sys.exit(1)
    
    health_root = Path(sys.argv[1])
    if not health_root.is_dir():
        print(f"Error: {health_root} is not a directory")
        sys.exit(1)

    person = sys.argv[2] if len(sys.argv) > 2 else health_root.parent.name
    
    index = generate_index(health_root, person)
    
    output_path = health_root / f"00_INDEX_{person}_Health.md"
    output_path.write_text(index, encoding="utf-8")
    print(f"✅ Index written to {output_path}")


if __name__ == "__main__":
    main()